"""ocamllsp resolution and the generated LSP plugin.

Which ocamllsp: `ocaml-lsp-server.1.15.1-4.14` installs into the project
switch beside dune 3.3.1 (it accepts dune-rpc 3.5 with the old dune), so
`opam install ocaml-lsp-server.1.15.1-4.14` there is the primary path and
leaves opam.export a superset. Newer releases (1.16+) force dune >= 3.4; for
one of those use a sibling switch with the same compiler, which is the
fallback resolved below. `mina-agent init` resolves the binary and writes a
plugin with its absolute path into harness/state/plugin; headless runs,
discuss, and the ~/.claude/skills symlink all point there.

After a dune version change, merlin configs in _build must be regenerated by
the current dune or ocamllsp reports every module as unbound:
`mina-agent exec -- dune build @src/check` does it for the whole tree once.

Resolution order:
  1. $MINA_AGENT_OCAMLLSP            explicit path
  2. ocamllsp on the activated PATH   (project switch, if someone put it there)
  3. opam var bin --switch mina-lsp   the sibling switch this harness documents
"""
import json
import os
import shutil
import subprocess

from . import paths

LSP_SWITCH = "mina-lsp"


def resolve(env):
    """Return (path, source) for the ocamllsp binary, or (None, reason)."""
    p = os.environ.get("MINA_AGENT_OCAMLLSP")
    if p:
        return (p, "MINA_AGENT_OCAMLLSP") if os.path.isfile(p) else (None, f"MINA_AGENT_OCAMLLSP={p} is not a file")
    aenv = env.activate() if env.mode != "none" else dict(os.environ)
    p = shutil.which("ocamllsp", path=aenv.get("PATH"))
    if p:
        return p, "PATH (project switch)"
    opam = shutil.which("opam")
    if opam:
        r = subprocess.run([opam, "var", "bin", f"--switch={LSP_SWITCH}"], capture_output=True, text=True)
        if r.returncode == 0:
            cand = os.path.join(r.stdout.strip(), "ocamllsp")
            if os.path.isfile(cand):
                return cand, f"opam switch {LSP_SWITCH}"
            return None, f"switch {LSP_SWITCH} exists but has no ocamllsp; opam install --switch={LSP_SWITCH} ocaml-lsp-server"
    return None, ("not found; install into the project switch: "
                  "opam install ocaml-lsp-server.1.15.1-4.14  (or a sibling switch: "
                  f"opam switch create {LSP_SWITCH} ocaml-base-compiler.4.14.2 && "
                  f"opam install --switch={LSP_SWITCH} ocaml-lsp-server)")


def write_plugin(repo, ocamllsp_path):
    """Generate harness/state/plugin from data/plugin with the resolved binary."""
    out = paths.generated_plugin(repo)
    (out / ".claude-plugin").mkdir(parents=True, exist_ok=True)
    shutil.copyfile(paths.PLUGIN / ".claude-plugin" / "plugin.json", out / ".claude-plugin" / "plugin.json")
    with open(paths.PLUGIN / ".lsp.json") as fh:
        lsp = json.load(fh)
    lsp["ocaml"]["command"] = ocamllsp_path
    with open(out / ".lsp.json", "w") as fh:
        json.dump(lsp, fh, indent=2)
        fh.write("\n")
    return out


def plugin_dir(repo):
    """The generated plugin if init produced one, else None."""
    out = paths.generated_plugin(repo)
    return out if (out / ".lsp.json").exists() else None


def link(repo):
    """Symlink the generated plugin into ~/.claude/skills so the user's own
    claude sessions load it (skills-directory plugins auto-load)."""
    target = paths.generated_plugin(repo)
    lnk = paths.SKILLS_DIR_LINK
    lnk.parent.mkdir(parents=True, exist_ok=True)
    if lnk.is_symlink():
        if lnk.resolve() == target.resolve():
            return lnk, "already linked"
        lnk.unlink()
    elif lnk.exists():
        return lnk, "exists and is not a symlink; left alone"
    lnk.symlink_to(target)
    return lnk, "linked"


def linked(repo):
    lnk = paths.SKILLS_DIR_LINK
    return lnk.is_symlink() and lnk.resolve() == paths.generated_plugin(repo).resolve()
