"""ocamllsp resolution and the generated LSP plugin.

The harness neither installs ocamllsp nor assumes how you would: an opam
switch, a nix devShell, a system package, a binary you built. It takes the
one it finds and complains loudly when there is none, because without it a
session loses Claude Code's LSP tool (goToDefinition, findReferences, hover,
workspaceSymbol) and falls back to merlin for type_at/definition alone.
`mina-agent admin init` resolves the binary and writes a plugin with its
absolute path into harness/state/plugin; headless runs, discuss, and the
~/.claude/skills symlink all point there.

Whatever you use has to agree with the repo's dune: ocamllsp talks dune-rpc,
and a build of it against a newer dune than the one on PATH reports every
module as unbound. So does a stale _build after a dune version change --
merlin configs there must be regenerated by the current dune, which
`mina-agent exec -- dune build @src/check` does for the whole tree once.

Resolution order:
  1. $MINA_AGENT_OCAMLLSP            explicit path
  2. ocamllsp on the activated PATH   (the nix devShell, the project switch,
                                       wherever you put it)
"""
import json
import os
import shutil

from . import paths
from .model import Mode


def resolve(env):
    """Return (path, source) for the ocamllsp binary, or (None, reason)."""
    p = os.environ.get("MINA_AGENT_OCAMLLSP")
    if p:
        return (p, "MINA_AGENT_OCAMLLSP") if os.path.isfile(p) else (None, f"MINA_AGENT_OCAMLLSP={p} is not a file")
    aenv = env.activate() if env.usable else dict(os.environ)
    p = shutil.which("ocamllsp", path=aenv.get("PATH"))
    if p:
        return p, "PATH (nix shell)" if env.mode is Mode.NIX else "PATH (project switch)"
    return None, ("no ocamllsp on PATH: sessions lose the LSP tool (goToDefinition, "
                  "findReferences, hover, workspaceSymbol) and fall back to merlin for "
                  "type_at/definition. Put one on PATH, or name it in MINA_AGENT_OCAMLLSP")


def write_plugin(repo, ocamllsp_path=None):
    """Generate <harness>/state/plugin from data/plugin: the manifest and the
    skills always; the LSP server entry only when ocamllsp resolved."""
    out = paths.generated_plugin()
    (out / ".claude-plugin").mkdir(parents=True, exist_ok=True)
    shutil.copyfile(paths.PLUGIN / ".claude-plugin" / "plugin.json", out / ".claude-plugin" / "plugin.json")
    if (out / "skills").exists():
        shutil.rmtree(out / "skills")
    shutil.copytree(paths.PLUGIN / "skills", out / "skills")
    lsp_out = out / ".lsp.json"
    if ocamllsp_path:
        with open(paths.PLUGIN / ".lsp.json") as fh:
            lsp = json.load(fh)
        lsp["ocaml"]["command"] = ocamllsp_path
        with open(lsp_out, "w") as fh:
            json.dump(lsp, fh, indent=2)
            fh.write("\n")
    elif lsp_out.exists():
        lsp_out.unlink()
    return out


def plugin_dir(repo):
    """The generated plugin if init produced one, else None."""
    out = paths.generated_plugin()
    return out if (out / ".claude-plugin" / "plugin.json").exists() else None


def has_lsp(repo) -> bool:
    return (paths.generated_plugin() / ".lsp.json").exists()
